import express from 'express';
import IncomeController from '../Controllers/Income';
import authMiddleware from '../Config/AuthMiddleware';
const router = express.Router();
router.post("/", authMiddleware, IncomeController.add);
router.get("/", authMiddleware, IncomeController.get);
router.get("/:id", authMiddleware, IncomeController.getIncomeId);
router.delete("/:id", authMiddleware, IncomeController.deleteIncome);
router.put("/:id", authMiddleware, IncomeController.updateIncome);
export default router;
